### ISSUE TITLE
1000 character limit on event descriptions

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#104]
The description will be truncated to 1000 characters. The input field should warn users that there is a 1000 character limit.

Now that most information that would previously go in the description has separate fields, descriptions can be focused on supporting text. The description no longer needs to include things like road segments being closed.

**Comment by inghamn** [comment]
It turns out we're currently chopping off our descriptions to 255 characters.  The form allows users to type lots of stuff that, then, gets truncated.

I believe we want to expand our descriptions from 255 to 1000 characters.
We should provide an alert or something when the user tries to type text than is supported.
The textarea should not display more text than is supported.   That way, the user can see what is actually going to saved in the database.
