### ISSUE TITLE
Event list should display location information

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#109]
Now that we're displaying the title on the event list, it means we're no longer displaying any location information there.

It seems like we should display at least one line of location information, too.  This can be generated from the segments, or it could be whatever the user typed into the Location field (which is what we used to display).

**Comment by inghamn** [comment]
Not sure what we really want to display here, anymore.  We've got title and/or human-typed location text, as well as the segments now.

**Comment by charlesbrandt** [comment]
I think it's fine to leave this set to the title as it is currently, unless someone else has a preference.

**Comment by hiesterd** [comment]
I came up with a few possibilities, talking with Cliff about it. I think since this part of the layout gets displayed in a larger typeface, our users would be best served if the information presented there helps them understand how this event impacts their drive.

We talked about many different combinations of how Title and Location could be used—whether together or separately—but seeing these comments, now, I think it could be simplest to just keep displaying the Title field, and have a clearer set of recommendations about what the Title of the event should be. For example, "Stormwater Project" is a less helpful Title to motorists scanning this list than "Fairview St," or "Fairview St from Wylie St to Dixie St."

**Comment by inghamn** [comment]
This issue has resurfaced
#150

**Comment by inghamn** [comment]
There's no real consensus from city employees as to what information goes into the title vs the location field.  We really do need to display both.

**Comment by rbdietz** [comment]
We need to provide a clear descriptions of what is expected in each of these fields.
