### ISSUE TITLE
Road events should have a spatial / visual component required

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#149]
Require that some type of spatial representation (line drawing) is added to an event

**Comment by inghamn** [comment]
Do we want to require the WAZE segments be entered as well?

**Comment by charlesbrandt** [comment]
Are there events that would not use WAZE segments that would be blocked by requiring them?

**Comment by inghamn** [comment]
Parking meters, Noise Permits, and Sidewalks have no WAZE information.   For that matter most parking meter reservations are entered without drawing anything on the map, since employees don't know where the parking meters are.

We need to make the eventTypes declare required information per event type
