### ISSUE TITLE
Send notice for unscheduled closures

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#151]
When an unscheduled closure occurs, it would be useful to be able to send a notification to a select list of emergency contacts. 

This would require: 
  - a custom field to add notes about the event
  - a way to mange who is on the emergency contact list

Related, but different from #144 
This feature would be manually triggered by staff. #144 would be automatically triggered for all new events.

**Comment by inghamn** [comment]
I don't know if it makes sense to set up additional google groups for new, arbitrary, sets of email addresses to notify.  Rather, inRoads should send the emails directly to a set of email addresses that we configure.

This and #144 are the same, in that inRoads will be sending emails directly to individual email addresses.  Are the emergency email addresses going to be people already in the system?  Or, should they be configured in site_config?

**Comment by charlesbrandt** [comment]
For this issue, the contacts to receive the message may not be in the system in any other way. Beyond that, I'm not sure where the best place to configure those would be.

**Comment by inghamn** [comment]
The email addresses that Bloomington wants to send emergency closure notices to is a mix of individual and group accounts.  I could kind of see having people sign themselves up for the emergency notifictions.  However, treating the group accounts as people is probably not the best.

I think we're going to need a configured list of email addresses to notify.  What user roles should be able to maintain that email list?  It seems like something that should be editable through the web interface?

**Comment by inghamn** [comment]
I think we probably want both: users should be able to subscribe themselves as well as a list of additional emails configured by an Admin or Staff person.

**Comment by inghamn** [comment]
How does this differ from just sending an email to a list of people?  If I displayed a list of emergency contact emails, would that be enough?

As I was about to build it, it was just going to be a text box for a user to type a message.  The inroads server would be responsible for emailing the message to all the email addresses on the contact list.  Rather than having the system send the email, can we let the user do this in their own email client?

**Comment by inghamn** [comment]
@charlesbrandt  and I talked about it, and decided there should be a preset message that goes out.  We want there to be a checkbox on Add Event screen for sending this notification out.  The system should already know what the message is, and notify everyone on the list about the newly-added event.

There should also be a button on the view event screen to send this notification out for any event in the system.

**Comment by inghamn** [comment]
With the desire to manage the notification lists in the web interface, the previous storage method was too confusing and compilcated.  I should redo it so that we just have two lists (probably tables) of email addresses.  A Person is gets notifications if their current email address is in that list.

That way, there can be email addresses that are not People and we only have a single place to look for notifications of a certain type.

The only additional complexity this would add is during Person::save() where we would need to update the email address in the notification list, if the Person has changed their email.

**Comment by inghamn** [comment]
This is a prerequisite for #193
